footprint: [[0.65,0.5],[-0.65,0.5],[-0.65,-0.5],[0.65,-0.5]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 0.5
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2
raytrace_range: 2.2

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_scan_front laser_scan_back 
    laser_scan_front: {sensor_frame: sick_laser_front_link , data_type: LaserScan, topic: sick_front/scan, marking: true, clearing: true}
    laser_scan_back: {sensor_frame: sick_laser_back_link , data_type: LaserScan, topic: sick_back/scan, marking: true, clearing: true}

inflation:
    inflation_radius: 2.3


radiationGlobal:
    radiation_topic: /radiation_front/color/image_raw
    radiation_radius: 0.5
    averaging_scale_length: 0.15  # Scale (variance mu of Gaussian kernel) in metres
    combination_method: 0  # default - 0 = UpdateWithMax, 1 = UpdateWithOverwrite, 2 = UpdateWithAddition, 3 = updateWithMaxPreserveNoInfo
    minimum_weight: 0.02  # default = 0.0, only update costmap with cells with weight above value

radiationLocal:
    radiation_topic: /radiation_front/color/image_raw
#    radiation_footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]]
    radiation_radius: 0.5
    averaging_scale_length: 0.15  # Scale (variance mu of Gaussian kernel) in metres
    combination_method: 0  # default - 0 = UpdateWithMax, 1 = UpdateWithOverwrite, 2 = UpdateWithAddition, 3 = updateWithMaxPreserveNoInfo
    minimum_weight: 0.02  # default = 0.0, only update costmap with cells with weight above value


temperatureGlobal:
    temperature_topic: /radiation_front/color/image_raw
    temperature_radius: 0.5
    averaging_scale_length: 0.15  # Scale (variance mu of Gaussian kernel) in metres
    combination_method: 0  # default - 0 = UpdateWithMax, 1 = UpdateWithOverwrite, 2 = UpdateWithAddition, 3 = updateWithMaxPreserveNoInfo
    minimum_weight: 0.02  # default = 0.0, only update costmap with cells with weight above value


temperatureLocal:
    temperature_topic: /radiation_front/color/image_raw
#    radiation_footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]]
    temperature_radius: 0.5
    averaging_scale_length: 0.15  # Scale (variance mu of Gaussian kernel) in metres
    combination_method: 0  # default - 0 = UpdateWithMax, 1 = UpdateWithOverwrite, 2 = UpdateWithAddition, 3 = updateWithMaxPreserveNoInfo
    minimum_weight: 0.02  # default = 0.0, only update costmap with cells with weight above value








# obstacle_range: 2
# raytrace_range: 2.0
# footprint: [[0.65,0.5],[-0.65,0.5],[-0.65,-0.5],[0.65,-0.5]]
# inflation_radius: 2.3
# cost_scaling_factor: 10.0

# observation_sources: laser_scan_front laser_scan_back 

# laser_scan_front: {sensor_frame: sick_laser_front_link , data_type: LaserScan, topic: sick_front/scan, marking: true, clearing: true}


# laser_scan_back: {sensor_frame: sick_laser_back_link , data_type: LaserScan, topic: sick_back/scan, marking: true, clearing: true}



